### ISSUE TITLE
Latest version 1.0.14 failed to load

### ISSUE THREAD

**Issue by xstrex** [shbatm/hacs-isy994#11]
I've tried upgrading to the latest version of the integration, and it's not loading properly for me. 

HA: 0.106.2
hacs-isy994: 1.0.12 & 1.0.14

HA spits out the obligatory, "this integration failed to load".. 

I've tried downgrading to 1.0.12, same issue, upgrading to 1.0.12, same issue. 
Next step is to remove & re-add entirely.  

Logs:
```
2020-02-29 11:23:18 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for isy994 which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-02-29 11:23:26 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #0
2020-02-29 11:23:28 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #1
2020-02-29 11:23:29 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #2
2020-02-29 11:23:30 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #3
2020-02-29 11:23:31 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #4
2020-02-29 11:23:32 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: retry #5
2020-02-29 11:23:32 ERROR (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/1 404: Failed after 5 retries
2020-02-29 11:23:32 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #0
2020-02-29 11:23:33 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #1
2020-02-29 11:23:34 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #2
2020-02-29 11:23:35 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #3
2020-02-29 11:23:36 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #4
2020-02-29 11:23:37 WARNING (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: retry #5
2020-02-29 11:23:37 ERROR (MainThread) [custom_components.isy994] Bad ISY Request: http://192.168.2.50:80/rest/vars/definitions/2 404: Failed after 5 retries
2020-02-29 11:23:37 ERROR (MainThread) [homeassistant.setup] Error during setup of component isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 170, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/isy994/__init__.py", line 484, in async_setup
    log=_LOGGER,
  File "/usr/local/lib/python3.7/site-packages/PyISY/isy.py", line 87, in __init__
    var_xml=self.conn.get_variables(),
  File "/usr/local/lib/python3.7/site-packages/PyISY/Variables/__init__.py", line 65, in __init__
    self.parse_definitions(def_xml)
  File "/usr/local/lib/python3.7/site-packages/PyISY/Variables/__init__.py", line 87, in parse_definitions
    xmldocs = [minidom.parseString(xml) for xml in xmls]
  File "/usr/local/lib/python3.7/site-packages/PyISY/Variables/__init__.py", line 87, in <listcomp>
    xmldocs = [minidom.parseString(xml) for xml in xmls]
  File "/usr/local/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
TypeError: a bytes-like object is required, not 'NoneType'
```

Let me know if you need more details, and thanks!

**Comment by shbatm** [comment]
What version ISY firmware are you using and are you trying to connect with HTTP or HTTPS?

**Comment by mbrunton77** [comment]
same thing for me.  had to revert back 1.0.11

**Comment by shbatm** [comment]
@mbrunton77 please provide the same information as requested above.

This version removes the automatic fallback to insecure communication with the ISY and I'm wondering if how you're connecting is the issue.

**Comment by jkrall** [comment]
Same problem here... 

* ISY firmware 5.0.13D
* No variables configured

I was accessing via `http://...:80` ... tried changing to `https://....` and now I'm getting the following error:
```
2020-03-01 22:39:04 ERROR (MainThread) [custom_components.isy994] PyISY cannot use HTTPS: Only TLS 1.1 and 1.2 are supported by the ISY controller.
2020-03-01 22:39:04 ERROR (MainThread) [custom_components.isy994] PyISY could not connect to the ISY. Check log for SSL/TLS error.
```

**Comment by mbrunton77** [comment]
> @mbrunton77 please provide the same information as requested above.
> 
> This version removes the automatic fallback to insecure communication with the ISY and I'm wondering if how you're connecting is the issue.

I am connecting using http in my configuration.yaml.   I can try https later tonight and report back with logs.

**Comment by shbatm** [comment]
Please update to the latest version and let me know if that fixes the issue. I believe the issue was with the code cleanup that added specific error types to be handled, I was missing TypeError.

This should not be related to HTTPS. If you weren't using HTTPS before, I would recommend NOT using it (as long as you are on your local network) as I believe there are still some issues with the ISYs HTTPS websockets and I'm not sure how stable it is.

**Comment by mbrunton77** [comment]
I just updated and everything seems to be working fine.  Thanks

**Comment by xstrex** [comment]
Agreed, upgraded to latest version and everything is working again. 

Thanks for your diligent work on this component, it’s greatly appreciated!
