### ISSUE TITLE
Clicking on Insteon scene in HA Overview UI errors 

### ISSUE THREAD

**Issue by jonsmirl** [shbatm/hacs-isy994#12]
Version 1.1

2020-03-06 18:10:01 WARNING (MainThread) [homeassistant.components.media_player] Updating roku media_player took longer than the scheduled update interval 0:00:10
2020-03-06 18:10:07 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1344947856] 'Group' object has no attribute 'on'
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/websocket_api/commands.py", line 134, in handle_call_service
    connection.context(msg),
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1230, in async_call
    await asyncio.shield(self._execute_service(handler, service_call))
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1253, in _execute_service
    await handler.func(service_call)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_component.py", line 198, in handle_service
    self._platforms.values(), func, call, required_features
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 402, in entity_service_call
    future.result()  # pop exception if have
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 590, in async_request_call
    await coro
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 433, in _handle_entity_call
    await result
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 615, in async_turn_on
    await self.hass.async_add_job(ft.partial(self.turn_on, **kwargs))
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/isy994/switch.py", line 61, in turn_on
    if not self._node.on():
AttributeError: 'Group' object has no attribute 'on'

**Comment by shbatm** [comment]
Thanks. Should be fixed in the latest version. Let me know if it isn't.
