### ISSUE TITLE
Exception while importing config flow

### ISSUE THREAD

**Issue by bdraco** [shbatm/hacs-isy994#27]
```
2020-03-15 21:51:37 ERROR (MainThread) [custom_components.isy994.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/isy994/config_flow.py", line 100, in async_step_user
    info = await validate_input(self.hass, user_input)
  File "/config/custom_components/isy994/config_flow.py", line 72, in validate_input
    log=_LOGGER,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'log'
```
Tracking it down now

**Comment by shbatm** [comment]
Closing as this looks like an install issue with PyISY Beta.
