### ISSUE TITLE
Error on startup with 1.0.8

### ISSUE THREAD

**Issue by bdraco** [shbatm/hacs-isy994#3]
Error during setup of component isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/isy994/__init__.py", line 482, in async_setup
    _categorize_nodes(hass, isy.nodes, ignore_identifier, sensor_identifier)
  File "/config/custom_components/isy994/__init__.py", line 348, in _categorize_nodes
    if _check_for_insteon_type(hass, node):
  File "/config/custom_components/isy994/__init__.py", line 198, in _check_for_insteon_type
    if domain == "binary_sensor" and int(node.nid[-1]) == 2:
ValueError: invalid literal for int() with base 10: 'D'

**Comment by jec6613** [comment]
Same issue here:

Error during setup of component isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 172, in _async_setup_component
    hass, processed_config
  File "/config/custom_components/isy994/__init__.py", line 479, in async_setup
    _categorize_nodes(hass, isy.nodes, ignore_identifier, sensor_identifier)
  File "/config/custom_components/isy994/__init__.py", line 347, in _categorize_nodes
    if _check_for_insteon_type(hass, node):
  File "/config/custom_components/isy994/__init__.py", line 200, in _check_for_insteon_type
    if domain == "binary_sensor" and int(node.nid[-1]) == 2:
ValueError: invalid literal for int() with base 10: 'D'

**Comment by shbatm** [comment]
Please try the `master` branch version in HACS and let me know if the issue is resolved. 

Thanks for the PR @bdraco, sorry I didn't see it at first.

**Comment by bdraco** [comment]
Pull master via HACS.  All is well now.

Thank you
