### ISSUE TITLE
Error while setting up isy994 platform for binary_sensor

### ISSUE THREAD

**Issue by mickdavis** [shbatm/hacs-isy994#41]
V 1.3.3 of the ISY994 component.
V 0.108.3 of HA

I'm getting the following error in the log:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 346, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/isy994/__init__.py", line 687, in device_info
    device_info["model"] += (
KeyError: 'model'

The same error is happening for a lock.

**Comment by mickdavis** [comment]
Still getting this error, just a different reason:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 328, in _async_write_ha_state
    attr.update(self.device_state_attributes or {})
  File "/config/custom_components/isy994/binary_sensor.py", line 473, in device_state_attributes
    if self._actions:
AttributeError: 'ISYBinarySensorProgram' object has no attribute '_actions'

**Comment by shbatm** [comment]
This should now be fixed in v1.3.6

**Comment by shbatm** [comment]
@mickdavis are you still having issues or can I close this?

**Comment by mickdavis** [comment]
I'm sorry, I didn't realize that you were waiting for me.

It's working great now. Thank you so much.
