### ISSUE TITLE
isy994 v1.3.3

### ISSUE THREAD

**Issue by timwing** [shbatm/hacs-isy994#42]
@shbatm I have tried another clean install of v1.3.3 on HA 0.108.3 and I am running into some issues.

![SNAG-0018](https://user-images.githubusercontent.com/60765858/79050741-07230f00-7bfa-11ea-92eb-feb62a5aed8b.png)

![SNAG-0019](https://user-images.githubusercontent.com/60765858/79050746-10ac7700-7bfa-11ea-808a-2d9f6864fa11.png)

No devices are showing
![SNAG-0020](https://user-images.githubusercontent.com/60765858/79050751-16a25800-7bfa-11ea-8af8-267553be52af.png)

The logs show the following just after installation via HACS then integrations.

```
2020-04-11 13:35:09 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry ISY - House (192.168.0.3) for isy994
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 216, in async_setup
    hass, self
  File "/config/custom_components/isy994/__init__.py", line 519, in async_setup_entry
    webroot=host.path,
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyisy/isy.py", line 93, in __init__
    self.networking = NetworkResources(self, xml=self.conn.get_network())
  File "/usr/local/lib/python3.7/site-packages/pyisy/networking.py", line 56, in __init__
    self.parse(xml)
  File "/usr/local/lib/python3.7/site-packages/pyisy/networking.py", line 65, in parse
    xmldoc = minidom.parseString(xml)
  File "/usr/local/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 13031
```

I only did an integration for 192.168.0.3 (House) but 192.168.0.2 (Shop) is also shown in states and they both have the same site_id:?

![SNAG-0021](https://user-images.githubusercontent.com/60765858/79050918-2f5f3d80-7bfb-11ea-9062-9c853691bb0d.png)

**Comment by shbatm** [comment]
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 13031

I'll push an update to catch this error, it looks like your Network Module is providing some bad XML for some reason.

> I only did an integration for 192.168.0.3 (House) but 192.168.0.2 (Shop) is also shown in states and they both have the same site_id:?

You're looking at the device trackers from your network (guessing Unifi?). That's not coming from the ISY integration, just the network integration showing they're online. Site ID is the same because they're on the same Unifi Site.
