### ISSUE TITLE
Config check not passing with the latest HACS component

### ISSUE THREAD

**Issue by rccoleman** [shbatm/hacs-isy994#47]
I'm not sure how long this has been going on, but I noticed that my config check is now failing with the following error, apparently during the installation of PyISY_beta.  The config works fine, including interop with the ISY and exposed Insteon devices, so this doesn't seem like a real runtime problem.

I'm currently running 0.108.5 of "supervised Home Assistant" and v0.24.0 of the custom component, but haven't yet gone back and see if these versions are problematic.  Is anyone else seeing something similar?

```
rcoleman@rcoleman-linux ~ % ./ha core check
Error: Testing configuration at /config
INFO:homeassistant.util.package:Attempting install of PyISY_beta==2.0.0rc4
ERROR:homeassistant.scripts.check_config:BURB
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              3028, in _dep_map
    return self.__dep_map
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              2822, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              3019, in _parsed_pkg_info
    return self._pkg_info
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              2822, in __getattr__
    raise AttributeError(attr)
AttributeError: _pkg_info

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/scripts/check_config.py", line 204,                                              in check
    async_check_ha_config_file(hass)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until                                             _complete
    return future.result()
  File "/usr/src/homeassistant/homeassistant/helpers/check_config.py", line 121,                                              in async_check_ha_config_file
    component = integration.get_component()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 268, in get_compon                                             ent
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_mod                                             ule
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/isy994/__init__.py", line 8, in <module>
    from pyisy import ISY
  File "/usr/local/lib/python3.7/site-packages/pyisy/__init__.py", line 29, in <                                             module>
    __version__ = pkg_resources.get_distribution("pyisy-beta").version
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              482, in get_distribution
    dist = get_provider(dist)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              358, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              795, in resolve
    new_requirements = dist.requires(req.extras)[::-1]
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              2743, in requires
    dm = self._dep_map
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              3030, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              3039, in _compute_dependencies
    for req in self._parsed_pkg_info.get_all('Requires-Dist') or []:
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              3021, in _parsed_pkg_info
    metadata = self.get_metadata(self.PKG_INFO)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              1422, in get_metadata
    value = self._get(path)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line                                              1618, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.                                             7/site-packages/urllib3-1.25.8.dist-info/METADATA'
Fatal error while loading config: [Errno 2] No such file or directory: '/usr/loc                                             al/lib/python3.7/site-packages/urllib3-1.25.8.dist-info/METADATA'
Failed config
  General Errors:
    - [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packag                                             es/urllib3-1.25.8.dist-info/METADATA'

Successful config (partial)
```

**Comment by rccoleman** [comment]
Well, it mysteriously seems to be better today.  In fact, the very same console window that stayed logged into my HA machine is now passing the same check that was failing yesterday.  The only thing that happened was that I restarted HA a few times yesterday, but I tried a restart yesterday and it didn't help.  I got nothin'.

**Comment by shbatm** [comment]
I had a similar issue a while back, there was something wrong with the way HASS was trying to install the PIP package, a couple restarts fixed it for me too.
