### ISSUE TITLE
HACS-isy994 - Climate module error

### ISSUE THREAD

**Issue by sbigras** [shbatm/hacs-isy994#50]
Hi again

this is tested with version HACS 1.3.6. on HASS 0.108.6

get a series of error with the climate module.

see log capture:

2020-04-22 15:31:06 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #0
2020-04-22 15:31:07 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #1
2020-04-22 15:31:08 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #2
2020-04-22 15:31:09 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #3
2020-04-22 15:31:10 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #4
2020-04-22 15:31:11 WARNING (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: retry #5
2020-04-22 15:31:11 ERROR (SyncWorker_7) [custom_components.isy994] Bad ISY Request: http://192.168.3.9:80/rest/vars/definitions/2 404: Failed after 5 retries
2020-04-22 15:31:13 ERROR (MainThread) [homeassistant.components.climate] Error while setting up isy994 platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 186, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 447, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/isy994/__init__.py", line 740, in state
    return super().state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 165, in state
    return self.hvac_mode
  File "/config/custom_components/isy994/climate.py", line 138, in hvac_mode
    return UOM_TO_STATES[self._node.aux_properties[CMD_CLIMATE_MODE].uom].get(
KeyError: 'n/a'
2020-04-22 15:31:13 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 320, in _async_write_ha_state
    state = self.state
  File "/config/custom_components/isy994/__init__.py", line 740, in state
    return super().state
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 165, in state
    return self.hvac_mode
  File "/config/custom_components/isy994/climate.py", line 138, in hvac_mode
    return UOM_TO_STATES[self._node.aux_properties[CMD_CLIMATE_MODE].uom].get(
KeyError: ''

last stack repeats 4 more times. 
The device is listed under the entities under configuration 

![Screenshot from 2020-04-22 17-01-30](https://user-images.githubusercontent.com/16723934/80033607-02444200-84bb-11ea-9658-9995ae5d19bd.png)

Thank for your work.

**Comment by shbatm** [comment]
What firmware are you running on the ISY?

Also, the first half of the errors about the Bad ISY Request for Variables, looks like you don't have any state variables defined. Not an issue, but if you want to get rid of that error, add a State Variable on the ISY.

**Comment by sbigras** [comment]
Hi, thank you for responding so quickly.

my ISY firmware is Insteon_UD994 v.4.7.3 and UI insteon_UD994 v.4.6.2.

Ref first error section, I was getting those before using the HACS-ISY
(using your ISY994 custom component module) but it did not affect the
performance/operation. BTW, the 2441th thermostat was properly recognised
under this configuration.

Thanks
sylvain

**Comment by shbatm** [comment]
OK. Looks like this is an issue with the way ISY v4 firmwares used the `UOM` property. I have a fix for it that I'll add to the next version. 

In the meantime, if you want (and you only have Insteon thermostats) -- in your `config/custom_components/isy944/` folder, change [line 138](https://github.com/shbatm/hacs-isy994/blob/09752ef35c1ccb483b5c958c7fd7848b5deebd4d/custom_components/isy994/climate.py#L138) of `climate.py` to this:

```python
return UOM_TO_STATES["98"].get(
```

**Comment by sbigras** [comment]
Thank you for the work-around.

Made the change, and the thermostat does re-appear. The thermostat is set
to celsius, HASS is set for celsius, but I get all sort of weird behaviour
when setting the low and high target temperature.

 it seems that as soon as a set the low target temperature let's say 20
degrees, the module doubles it up to 40. and shortly after the high target
temperature adjusts in a logic that I have not figured out yet.

[image: image.png]

Would you like me to open a different issue ticket?

Thanks
Sylvain

**Comment by shbatm** [comment]
OK. I've seen that before and I think it was fixed for ISYv5 firmware, but I guess not for v4... it stems from Fahrenheit having w 

Can you please send me the results of http://192.168.3.9:80/rest/nodes/TSTAT ADDRESS from your browser? Should be an xml file.
