### ISSUE TITLE
Websocket disconnected unexpectedly with code: 0 and 1006

### ISSUE THREAD

**Issue by autoneub** [shbatm/hacs-isy994#86]
Received this error almost 7000 times in 3 hours overnight. Not sure if it's related, but my Query All program runs at 3am.
```
Logger: pyisy.events.websocket
Source: deps/lib/python/site-packages/pyisy/events/websocket.py:263
First occurred: 3:22:32 AM (6853 occurrences)
Last logged: 6:00:01 AM

Websocket disconnected unexpectedly with code: 0
Websocket disconnected unexpectedly with code: 1006
```

Devices are unresponsive until a reboot of HA.

After the first couple of the above Warnings, the following error occured. I believe it was triggered by an automation that turns on a KPL button (via ISY Scene) when my outdoor patio bulbs are on.

```
2021-04-01 03:05:07 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall switch.turn_on (c:2a9d3e2685a3cf640bcd47a632c2985e): entity_id=['switch.patio_bulbs_button']>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/core.py", line 1504, in catch_exceptions
    await coro_or_task
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/core.py", line 1523, in _execute_service
    await handler.job.target(service_call)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 642, in entity_service_call
    future.result()  # pop exception if have
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 681, in async_request_call
    await coro
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 679, in _handle_entity_call
    await result
  File "/Users/neuby/.homeassistant/custom_components/isy994/switch.py", line 50, in async_turn_on
    if not await self._node.turn_on():
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/nodes/nodebase.py", line 336, in turn_on
    return await self.send_cmd(cmd, val)
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/nodes/nodebase.py", line 252, in send_cmd
    if not await self.isy.conn.request(req_url):
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/connection.py", line 197, in request
    retry_result = await self.request(url, retries + 1, ok404=False)
  [Previous line repeated 2 more times]
  File "/Users/neuby/.homeassistant/deps/lib/python/site-packages/pyisy/connection.py", line 203, in request
    res.status,
UnboundLocalError: local variable 'res' referenced before assignment
```

I'm running HA 2021.3.1 on macOS python 
v3.0.0dev19 of this integration.
ISY firmware v5.3.0

I just realized that my ISY is the PRO version and I'm using TLS 1.1 in the core ISY integration. Not sure if that would be pertinent.

**Comment by autoneub** [comment]
So earlier I removed both integrations, reinstalled and rebooted. I set the TLS as 1.2. 

So far so good but I’m going to see how it handles the overnight query. 
Will report back

**Comment by autoneub** [comment]
Received the same errors this morning but not right after the query. Upon reloading the integration with a service call (which then required a reboot) it’s all good again. 

Not sure why this is happening but happy to troubleshoot with some instruction.

**Comment by autoneub** [comment]
So disabling the query program kept the connection overnight. Maybe the connection gets bogged down with all that traffic all at once. Something think about, but for now I’ll close the issue.
