### ISSUE TITLE
Door Locks and data.

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#97]
Setting the door lock:
![image](https://user-images.githubusercontent.com/11697710/221286718-3c258888-fd71-43c6-8a5d-f52c65184eb8.png)

Errors with:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:36:13 PM (3 occurrences)
Last logged: 12:37:27 PM

[139737524569568] Error handling message: required key not provided @ data['code']. Got None (invalid_format) from 172.16.5.71 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
[139737524569568] Error handling message: extra keys not allowed @ data['code']. Got None (invalid_format) from 172.16.5.71 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
```

Deleting Door Lock:
![image](https://user-images.githubusercontent.com/11697710/221287179-76e9d636-8da3-42ca-a12e-b297a5982cfb.png)

Errors with:
```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:150
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 12:36:13 PM (4 occurrences)
Last logged: 12:39:54 PM

[139737524569568] Error handling message: required key not provided @ data['code']. Got None (invalid_format) from 172.16.5.71 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
[139737524569568] Error handling message: extra keys not allowed @ data['code']. Got None (invalid_format) from 172.16.5.71 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
```

**Comment by MechEng70** [comment]
Are these switched in the services.py?

```
SERVICE_SET_USER_CODE_SCHEMA = {vol.Required(CONF_USER_NUM): vol.Coerce(int)}
SERVICE_DELETE_USER_CODE_SCHEMA = {
    vol.Required(CONF_USER_NUM): vol.Coerce(int),
    vol.Required(CONF_CODE): vol.Coerce(int),
}
```

Shouldn't it be this way?

```
SERVICE_DELETE_USER_CODE_SCHEMA = {vol.Required(CONF_USER_NUM): vol.Coerce(int)}
SERVICE_SET_USER_CODE_SCHEMA = {
    vol.Required(CONF_USER_NUM): vol.Coerce(int),
    vol.Required(CONF_CODE): vol.Coerce(int),
}
```

**Comment by shbatm** [comment]
Closed via #98

**Comment by MechEng70** [comment]
New Error:
```
2023-02-24 16:50:01.302 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2023-02-24 16:50:01.303 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-02-24 16:50:01.304 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Cannot set parameters of non-Z-Wave device
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/isy994/lock.py", line 67, in async_set_zwave_lock_user_code
    if not await self._node.set_zwave_lock_code(user_num, code):
  File "/usr/local/lib/python3.10/site-packages/pyisyox/nodes/node.py", line 417, in set_zwave_lock_code
    raise TypeError("Cannot set parameters of non-Z-Wave device")
TypeError: Cannot set parameters of non-Z-Wave device
2023-02-24 16:50:01.306 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140473531334128] Error handling message: Unknown error (unknown_error) from 172.16.4.1 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/isy994/lock.py", line 67, in async_set_zwave_lock_user_code
    if not await self._node.set_zwave_lock_code(user_num, code):
  File "/usr/local/lib/python3.10/site-packages/pyisyox/nodes/node.py", line 417, in set_zwave_lock_code
    raise TypeError("Cannot set parameters of non-Z-Wave device")
TypeError: Cannot set parameters of non-Z-Wave device
```

**Comment by shbatm** [comment]
Which node and Entity_id did you call the service on?

**Comment by MechEng70** [comment]
ZY087_1 - which is what the lock.front shows up as.

Here is the lock screen shot from AC:
![image](https://user-images.githubusercontent.com/11697710/221327956-f53fb8c0-6f02-4473-a584-3340c6c5d5c6.png)

**Comment by MechEng70** [comment]
The User button also shows up under 306.

![image](https://user-images.githubusercontent.com/11697710/221328036-aebada5b-15b3-4535-80f0-58d975cb167d.png)

**Comment by shbatm** [comment]
I think I found the problem [here](https://github.com/shbatm/pyisyox/pull/12/files). Try the latest (4.0.9).

**Comment by MechEng70** [comment]
Deleting using Entity works. Can see that the user is deleted:

![image](https://user-images.githubusercontent.com/11697710/221329597-fb827b33-5eba-4e66-8a6b-7f4bd42a838e.png)


Setting a User code does not through an error in HA, but doesn't do anything in ISY.

**Comment by shbatm** [comment]
Ok. 5th times a charm. Try 4.0.10

**Comment by MechEng70** [comment]
Nailed it!

**Comment by MechEng70** [comment]
Thank you!

**Comment by MechEng70** [comment]
Working as intended.
